# Generated by Django 4.0.3 on 2023-04-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=256)),
                ('codes', models.SlugField()),
                ('validity', models.CharField(max_length=256)),
            ],
        ),
    ]
