# Generated by Django 4.0.3 on 2023-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='keyword_len',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='proj_len',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
